name: Build and Release

on:
  push:
    branches:
      - main

jobs:

  get_version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.set_version.outputs.version }}

    steps:
      - id: set_version
        run: echo ::set-output name=version::$(node -pe "require('./package.json').version")


  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Release app
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          token: ${{ secrets.build_token }}
          tag_name: v${{ steps.get_version.outputs.version }}
          body: Automated release
