name: Build/test

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs: 
  test-build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            args: -w
          - os: ubuntu-22.04
            args: -l
          - os: macos-latest
            args: -m

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --force

      - name: Build/release Electron app
        uses: DeadCodeGames/action-electron-builder@effa1ea435ec026b5c7b953273d18d55b17b5d04
        with:
          github_token: ${{ secrets.build_token }}
          args: ${{ matrix.args }}
          build_script_name: "full-build"
          skip_install: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages ${{matrix.os}}
          path: dist